### PR TITLE
Fix a bug with [@@deriving make] on type declarations sets

### LINKED ISSUE #272: `ppx_deriving.make` breaks on mutually recurive types
In `ex.ml`

```ocaml
module Ex = struct
  type t = {a : int; b: s}
  [@@deriving make]
  and s = t list
end
```

With the `dune` file:

```scheme
(library
 (name ex)
 (modules ex)
 (preprocess (pps ppx_deriving.make)))
```

`dune build` gives

```sh
$ dune build                    
File "ex.ml", line 5, characters 2-16:
5 |   and s = t list
      ^^^^^^^^^^^^^^
Error: make can be derived only for record types
```

If we put another deriving annotation on `s` and swap the order the types are declared, the compilation goes thru but the `make` annotation is ignored:

```ocaml
module Ex = struct
  type s = t list
  [@@deriving show]

  and t = {a : int; b: s}
  [@@deriving make]
end
```

Which produces

```ocaml
[@@@ocaml.ppx.context
  {
    tool_name = "ppx_driver";
    include_dirs = [];
    load_path = [];
    open_modules = [];
    for_package = None;
    debug = false;
    use_threads = false;
    use_vmthreads = false;
    recursive_types = false;
    principal = false;
    transparent_modules = false;
    unboxed_types = false;
    unsafe_string = false;
    cookies = [("library-name", "ex")]
  }]
module Ex =
  struct
    type s = t list[@@deriving show]
    and t = {
      a: int ;
      b: s }[@@deriving make]
    let rec pp_s :
      Ppx_deriving_runtime.Format.formatter -> s -> Ppx_deriving_runtime.unit
      =
      let __0 () = pp in
      ((let open! ((Ppx_deriving_runtime)[@ocaml.warning "-A"]) in
          fun fmt ->
            fun x ->
              Ppx_deriving_runtime.Format.fprintf fmt "@[<2>[";
              ignore
                (List.fold_left
                   (fun sep ->
                      fun x ->
                        if sep
                        then Ppx_deriving_runtime.Format.fprintf fmt ";@ ";
                        ((__0 ()) fmt) x;
                        true) false x);
              Ppx_deriving_runtime.Format.fprintf fmt "@,]@]")
        [@ocaml.warning "-A"])
    and show_s : s -> Ppx_deriving_runtime.string =
      fun x -> Ppx_deriving_runtime.Format.asprintf "%a" pp_s x[@@ocaml.warning
                                                                 "-32"]
    and pp :
      Ppx_deriving_runtime.Format.formatter -> t -> Ppx_deriving_runtime.unit
      =
      let __0 () = pp_s in
      ((let open! ((Ppx_deriving_runtime)[@ocaml.warning "-A"]) in
          fun fmt ->
            fun x ->
              Ppx_deriving_runtime.Format.fprintf fmt "@[<2>{ ";
              ((Ppx_deriving_runtime.Format.fprintf fmt "@[%s =@ " "Ex.Ex.a";
                (Ppx_deriving_runtime.Format.fprintf fmt "%d") x.a;
                Ppx_deriving_runtime.Format.fprintf fmt "@]");
               Ppx_deriving_runtime.Format.fprintf fmt ";@ ";
               Ppx_deriving_runtime.Format.fprintf fmt "@[%s =@ " "b";
               ((__0 ()) fmt) x.b;
               Ppx_deriving_runtime.Format.fprintf fmt "@]");
              Ppx_deriving_runtime.Format.fprintf fmt "@ }@]")
        [@ocaml.warning "-A"])
    and show : t -> Ppx_deriving_runtime.string =
      fun x -> Ppx_deriving_runtime.Format.asprintf "%a" pp x[@@ocaml.warning
                                                               "-32"]
  end
```

As per `dune describe pp ex.ml`.

If the additional deriving annotation is not added, we get the same error.

### PR DESCRIPTION
**Pull request by NathanReb**
Fixes #272.

There was a bug with `[@@deriving make]` that caused errors if it was used on a set of type declarations, recursive or non recursive, that contained a non record type.

The deriver was applied to all type declarations in the set, regardless of where the attributes was attached and failed on the ones that weren't record types.

There is no particularly nice way to handle this in ppxlib, I assume the design decision was that one would only attach a single `[@@deriving ...]` attribute per set and the individual derivers would be responsible to decide which type declarations are relevant.
The driver does allow attaching multiple `[@@deriving ...]` attributes in the same set but performs a merge of all of them so it can lead to confusing situations for the end user.

With all that in mind, there is currently no proper way to tell to which individual type declarations the deriver was attached and even though there might be a hacky one, I'm not sure it would be desirable to use it as it's unlikely that other derivers do so and we probably don't want to have `ppx_deriving.make` behave differently to the rest of the ppx universe in that regard.

The fix will derive `make` for all record types in the set if there is at least one, or will report errors about a misuse of the
deriver otherwise.

The PR contains the initial regression test added in #273 by @shonfeder along with a small refactoring to properly embed errors. This allows us to treat regular errors, for example errors coming from misuse of `[@main]` or `[@split]`, and the `make can only be derived for record types` error differently which we use for the actual fix.

I also updated the README to document how to use `ppx_deriving.make` with type declaration sets.

### CODE REVIEW

**Comment by NathanReb** [comment]
@sim642 I'm pinging you in case you're interested in reviewing this. I'd recommend the per-commit view here, although I'm happy to split out the error handling bits if it makes the review easier.

I was hoping to get the fix in before hitting a new `6.0` release.

File: src_plugins/make/ppx_deriving_make.ml [hunk 1]
```diff
@@ -11,126 +11,162 @@ let attr_default context = Attribute.declare "deriving.make.default" context
...
+        when name.[String.length name - 1] = 's' ->
+        let name' = String.sub name 0 (String.length name - 1) in
+        Typ.arrow (Label.labelled name') lhs
+          (Typ.arrow (Label.optional name)
+             (wrap_predef_option [%type: [%t rhs] list]) accum)
+      | _ ->
+        Ast_builder.Default.ptyp_extension ~loc
+          (Location.error_extensionf ~loc
+             "[@deriving.%s.split] annotation requires a type of form \
+              'a * 'b list and label name ending with `s'"
```
Comment (sim642) [inline src_plugins/make/ppx_deriving_make.ml:137]: Should the `'b` also be changed here?

Comment (NathanReb) [reply src_plugins/make/ppx_deriving_make.ml:137]: That's right, good catch!
